matrix:
  include:
    - language: node_js
      node_js:
        - 14.10.0
      cache: npm

      before_install:
        - cd FrontEnd

      install:
        - npm ci

      script:
        - npm test
        - npm run build

      after_success:
        - echo "Finished FrontEnd Testing"

    - language: python
      python:
        - 3.6

      install:
        - pip install -r requirements.txt
        - pip install pytest pytest-cov

      script:
        - pytest --pylint
        - cd BackEnd
        - python tests/test_api.py
        - cd ..
        - coverage run --source=BackEnd -m pytest BackEnd/tests/
        - coveralls

      after_success:
        - echo "Finished BackEnd Testing"

notifications:
  email:
    - ppenmet@ncsu.edu
    - sadhika2@ncsu.edu
    - sray9@ncsu.edu
    - nshukla2@ncsu.edu
    - dshah4@ncsu.edu