matrix:
  include:
    - language: node_js
      node_js:
        - 14.10.0
      cache: npm

      before_install:
        - cd FrontEnd

      install:
        - npm ci

      script:
        - npm test
        - npm run build

      after_success:
        - echo "Finished FrontEnd Testing"


    - language: python
      python:
        - 3.6

      install:
        - pip install -r requirements.txt

      script:
        - pwd
        - cd BackEnd
        - python test/test_api.py

      after_success:
        - echo "Finished BackEnd Testing"

notifications:
  email:
    - ppenmet@ncsu.edu
    - sadhika2@ncsu.edu
    - sray9@ncsu.edu
    - nshukla2@ncsu.edu
