language: node_js

node_js:
  - 14.10.0
cache: npm

before_install:
  - cd Front-End

install:
  - npm ci

script:
  - npm test
  - npm run build 

notifications:
 email:
   - ppenmet@ncsu.edu
   - sadhika2@ncsu.edu
   - sray9@ncsu.edu
   - nshukla2@ncsu.edu